#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/deploy-laravel-app

- name: Execute Laravel maintenance commands
  command: "{{ item }}"
  args:
    chdir: "{{ PROJECT_PATH }}"
  loop:
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan horizon:terminate