---

### General variables

PROJECT_GITHUB_REPO: "https://github.com/tchedem/simple-laravel-api-with-performance.git"
PROJECT_GITHUB_BRANCH: main
PROJECT_PATH: /var/www/local/performance_api

system_user: vagrant
PROJECT_USER: www-data
PROJECT_GROUP: www-data

PROJECT_DOMAIN_NAME: performance-api.com
PROJECT_NUMBER_OF_HORIZON_PROCESSES: 2

GENERATE_APP_KEY: False

### Project specific variables 

APP_NAME: performance-api
# APP_ENV: test
# APP_ENV: staging
# APP_ENV: prod
APP_ENV: local
# APP_KEY: "base64:v9d6lqDmIRYthsOsG44qsaGC4ps4GFmvhWfMSMb/Xr4:"
APP_DEBUG: true

APP_URL: http://performance-api.com
# APP_URL: 127.0.0.1:8000
APP_VERSION: 1.0.0

TEMP_BEARER_TOKEN: 

LOG_CHANNEL: single
LOG_LEVEL: debug

# Simple DB Config
DB_CONNECTION: mysql
DB_HOST: 127.0.0.1
DB_PORT: 3306
DB_DATABASE: "performance-api_db"
DB_USERNAME: "laravel-user"
DB_PASSWORD: "98@12*POasxfuybve"

# MONGODB_HOST: 127.0.0.1
# MONGODB_PORT: 27017
# MONGODB_DATABASE: "performance-api_db"
# MONGODB_USERNAME: "laravel-user"
# MONGODB_PASSWORD: "98@12*POasxfuybve"

BROADCAST_DRIVER: log
CACHE_DRIVER: file
FILESYSTEM_DISK: local

# BROADCAST_DRIVER: log
QUEUE_CONNECTION: sync
# QUEUE_CONNECTION: redis
# QUEUE_CONNECTION: database
# SESSION_DRIVER: redis
SESSION_DRIVER: file
SESSION_LIFETIME: 3600
SESSION_DOMAIN: .performance-api.com

# MEMCACHED_HOST: 127.0.0.1

# CACHE_DRIVER: redis
REDIS_CLIENT: predis
REDIS_HOST: 127.0.0.1
REDIS_PASSWORD: "7e024176-3c36-4e6e-89ac-ea608a41e40bb7725410-c8ca-47fa-b2b9-385f4305dcd3"
REDIS_PORT: 6379
