#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/certbot

- name: Install Certbot and Nginx if not installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - certbot
    - python3-certbot-nginx

  